from kitti_model_config import kitti_model_config
from kitti_squeezeDet_config import kitti_squeezeDet_config

from bdd_squeezeDet_config import bdd_squeezeDet_config
from nightowls_squeezeDet_config import nightowls_squeezeDet_config
from synscapes_squeezeDet_config import synscapes_squeezeDet_config
from a2d2_squeezeDet_config import a2d2_squeezeDet_config
from nuimages_squeezeDet_config import nuimages_squeezeDet_config

from kitti_3cls_squeezeDet_config import kitti_3cls_squeezeDet_config
from bdd_3cls_squeezeDet_config import bdd_3cls_squeezeDet_config
from nightowls_3cls_squeezeDet_config import nightowls_3cls_squeezeDet_config
from synscapes_3cls_squeezeDet_config import synscapes_3cls_squeezeDet_config
from a2d2_3cls_squeezeDet_config import a2d2_3cls_squeezeDet_config
from nuimages_3cls_squeezeDet_config import nuimages_3cls_squeezeDet_config